version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: Etc/UTC
    open-pull-requests-limit: 10
    versioning-strategy: increase
    commit-message:
      prefix: chore(deps)
      include: scope
    groups:
      types:
        patterns:
          - '@types/*'
      eslint:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
          - 'typescript-eslint'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: Etc/UTC
    commit-message:
      prefix: chore(ci)
      include: scope
